name: it3105_proj2
channels:
  - default
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - flake8
  - pylint
  - pyyaml
  - matplotlib
  - numpy
  - pytorch 
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - cudatoolkit-dev
  - pygame
  - pip
  - pip:
    - -e .
